name: on-push
on: [push, pull_request]
env:
  MIX_ENV: test
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - pair:
              otp: 27.x
              elixir: 1.17.x
              lint: lint

          - pair:
              otp: 26.x
              elixir: 1.17.x
          - pair:
              otp: 26.x
              elixir: 1.16.x
          - pair:
              otp: 26.x
              elixir: 1.15.x

          - pair:
              otp: 25.x
              elixir: 1.17.x
          - pair:
              otp: 25.x
              elixir: 1.16.x
          - pair:
              otp: 25.x
              elixir: 1.15.x
          - pair:
              otp: 25.x
              elixir: 1.14.x

          - pair:
              otp: 24.x
              elixir: 1.16.x
          - pair:
              otp: 24.x
              elixir: 1.15.x
          - pair:
              otp: 24.x
              elixir: 1.14.x
          - pair:
              otp: 24.x
              elixir: 1.13.x

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
          version-type: strict
      - uses: actions/cache@v3
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{matrix.pair.otp}}-${{matrix.pair.elixir}}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-${{matrix.pair.otp}}-${{matrix.pair.elixir}}-
      - run: mix deps.get
      - run: mix compile
      - run: mix format --check-formatted
        if: ${{matrix.lint}}
      - run: mix dialyzer
        if: ${{matrix.lint}}
      - run: mix test
